#!/bin/zsh

# --- 1. User-Only Plugins (Skip for Root) ---
if [[ $UID -ne 0 ]]; then
  [[ -r ~/.plugins/znap/znap.zsh ]] || git clone --depth 1 -- https://github.com/marlonrichert/zsh-snap.git ~/.plugins/znap
  source ~/.plugins/znap/znap.zsh

  znap source marlonrichert/zsh-autocomplete
  znap source zsh-users/zsh-syntax-highlighting
  znap source zsh-users/zsh-autosuggestions
  znap source marlonrichert/zcolors
  znap source mrjohannchang/zsh-interactive-cd
  znap eval zcolors "zcolors ${(q)LS_COLORS}"
fi

# --- 2. Homebrew & Path Configuration ---
export HOMEBREW_NO_ENV_HINTS=true
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"

if [[ $UID -ne 0 ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"

  # Brew-dependent compiler flags (Only for non-root)
  export LDFLAGS="-L$(brew --prefix openssl@3)/lib -L$(brew --prefix readline)/lib"
  export CPPFLAGS="-I$(brew --prefix openssl@3)/include -I$(brew --prefix readline)/include"
  export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@3) --with-readline-dir=$(brew --prefix readline)"
fi

# Language-specific Paths
export PATH="/opt/homebrew/opt/node@22/bin:/opt/homebrew/opt/php@8.4/bin:$HOME/.rbenv/bin:$PATH"
export CFLAGS="-Wno-error=implicit-function-declaration"

# --- 3. Tool Initializations ---
# These now work for root because /opt/homebrew/bin is in the PATH
eval "$(atuin init zsh)"
eval "$(zoxide init zsh --cmd cd)"
eval "$(oh-my-posh init zsh --config '/Users/nr/Workspaces/github/ohmyposh.theme/_Nordic_2026.omp.json')"

# Version Managers
eval "$(rbenv init -)"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# --- 4. Environment Variables ---
export VAGRANT_DEFAULT_PROVIDER="virtualbox"
export WEZTERM_THEME="dark"

# --- 5. SDKMAN (Must be last) ---
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"