#!/bin/sh

#export ZSH=$HOME/.oh-my-zsh

#plugins=(
#    git
#    z
#    git-flow
#    git-extras
#    zsh-autosuggestions
#    zsh-syntax-highlighting
#    )

#source $ZSH/oh-my-zsh.sh


if [ -d ~/.shell ]; then
    . $HOME/.shell/sources
    . $HOME/.shell/aliases
fi

#source $ZSH/oh-my-zsh.sh
# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/nr/.lmstudio/bin"
# End of LM Studio CLI section

# Load Angular CLI autocompletion.
source <(ng completion script)

