#!/bin/zsh

#export ZSH=$HOME/.oh-my-zsh

#plugins=(
#    git
#    z
#    git-flow
#    git-extras
#    zsh-autosuggestions
#    zsh-syntax-highlighting
#    )

#source $ZSH/oh-my-zsh.sh


if [ -d ~/.shell ]; then
   . $HOME/.shell/gsources
   . $HOME/.shell/aliases
fi

#source $ZSH/oh-my-zsh.sh
# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/nr/.lmstudio/bin"
# End of LM Studio CLI section

# Load Angular CLI autocompletion.
source <(ng completion script)
#export TERM="wezterm"
if [[ "$TERM" != "xterm-256color" ]]; then
  export TERM="xterm-256color"
fi
#eval "$(rbenv init -)"
#export PYENV_ROOT="$HOME/.pyenv"
#[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init - zsh)"
#
export PAGER="less -RF"
